# Generated by Django 3.1.7 on 2021-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
