# Generated by Django 3.1.7 on 2021-03-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210325_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='id',
            new_name='staff_id',
        ),
    ]
