# Generated by Django 3.1.7 on 2021-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staff_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
