# Generated by Django 3.1.7 on 2021-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210329_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_other',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_receptionist',
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
