# Generated by Django 3.1.7 on 2021-03-30 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210329_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
    ]
