# Generated by Django 3.1.7 on 2021-03-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210325_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facility',
            table='facility',
        ),
    ]
