# Generated by Django 3.1.7 on 2021-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210325_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
