# Generated by Django 3.1.7 on 2021-03-30 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_guest'),
        ('main', '0012_auto_20210330_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('no_children', models.PositiveIntegerField(default=0)),
                ('no_adults', models.PositiveIntegerField(default=0)),
                ('expected_arrival_date_time', models.DateField(default=django.utils.timezone.now)),
                ('expected_departure_date_time', models.DateField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guest')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reservation'),
        ),
    ]
