# Generated by Django 3.1.7 on 2021-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210330_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('Double Suit', 'Double Suit'), ('Luxury Suit', 'Luxury Suit'), ('Exclusive Suit', 'Exclusive Suit'), ('EXECUTIVE FLOOR', 'EXECUTIVE FLOOR'), ('SUPERIOR ROOM', 'SUPERIOR ROOM'), ('BUSINESS SUITE', 'BUSINESS SUITE'), ('STATE SUITE', 'STATE SUITE')], max_length=30),
        ),
    ]
